# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MidiService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MidiService.proto\x12\x11\x63om.card.api.grpc\"2\n\x14\x41\x63tivateColorRequest\x12\x0b\n\x03pad\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x01 \x01(\t\"#\n\x15\x41\x63tivateColorResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32s\n\x0bMidiService\x12\x64\n\ractivateColor\x12\'.com.card.api.grpc.ActivateColorRequest\x1a(.com.card.api.grpc.ActivateColorResponse\"\x00\x42\'\n#net.devh.boot.grpc.card.service.libP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MidiService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#net.devh.boot.grpc.card.service.libP\001'
  _globals['_ACTIVATECOLORREQUEST']._serialized_start=40
  _globals['_ACTIVATECOLORREQUEST']._serialized_end=90
  _globals['_ACTIVATECOLORRESPONSE']._serialized_start=92
  _globals['_ACTIVATECOLORRESPONSE']._serialized_end=127
  _globals['_MIDISERVICE']._serialized_start=129
  _globals['_MIDISERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
